CREATE DATABASE BLOG_CULINARIA;
USE BLOG_CULINARIA;

-- CRIACAO DAS TABELAS SEM CHAVE ESTRANGEIRA
-- PRIMEIRA TABELA, USUARIOS
CREATE TABLE USUARIOS
(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(60) NOT NULL,
    SENHA VARCHAR(45) NOT NULL,
    EMAIL VARCHAR(90) NOT NULL,
    FOTO VARCHAR(350),
    -- ESSE TIPO_CONTA SERVE PARA DIVIDAR AS CONTAS DE COMUM PRA ADMINISTRADOR
    -- ENTRETANTO NO SISTEMA NA HORA DE CRIAR AS CONTAS ELAS SERÃO SETADAS PARA COMUM DIRETO
    -- E PARA SE TER UMA CONTA DE ADMINISTRADOR É NECESSÁRIO QUE SEJA ALTERADO NO SISTEMA POR FORA DENTRO DE OUTRO PROGRAMA
    TIPO_CONTA VARCHAR(15),
    
    PRIMARY KEY(ID)
)
ENGINE = INNODB;

-- SEGUNDA TABELA, POSTS
CREATE TABLE POSTS
( 
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	TITULO VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(250) NOT NULL,
    CONTEUDO VARCHAR(1000) NOT NULL,
    INGREDIENTES VARCHAR(350) NOT NULL,
    IMAGEM VARCHAR(250),
    PRIMARY KEY(ID)
)
ENGINE = INNODB;
-- -----------------------------------------

-- CRIACAO DAS TABELAS COM CHAVE ESTRANGEIRA
-- PRIMEIRA TABELA, FAVORITOS

CREATE TABLE FAVORITOS
( 
	CODIGO INT UNSIGNED NOT NULL AUTO_INCREMENT,
    POST_ID INT UNSIGNED NOT NULL,
    USER_ID INT UNSIGNED NOT NULL,
    
    PRIMARY KEY(CODIGO),
    -- CHAVE ESTRANGEIRA
    FOREIGN KEY(POST_ID) REFERENCES POSTS(ID),
    FOREIGN KEY(USER_ID) REFERENCES USUARIOS(ID)
)
ENGINE = INNODB;

-- SEGUNDA, TABELA COMENTARIOS
CREATE TABLE COMENTARIOS
( 
	CODIGO INT UNSIGNED NOT NULL AUTO_INCREMENT,
    CONTEUDO VARCHAR(300),
    POST_ID INT UNSIGNED NOT NULL,
    USER_ID INT UNSIGNED NOT NULL,
    
    PRIMARY KEY(CODIGO)
)
ENGINE = INNODB;
SET foreign_key_checks = 0;
-- -----------------------------------------

